[package]
name = "eureka-finder"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
rand = "0.9.2"
getrandom = { version = "0.3", features = ["wasm_js"] }
rayon = "1.11.0"
num = "0.4.3"
regex = "1.11.2"
lazy_static = "1.5.0"
wasm-bindgen = "0.2.100"
js-sys = "0.3.77"